# Generated by Django 3.0.4 on 2021-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Subject')),
                ('company_name', models.CharField(max_length=50, null=True, verbose_name='Company Name')),
                ('content', models.TextField(null=True, verbose_name='Content')),
            ],
        ),
    ]
